name: Continuous Integration

on: push

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/setup-uv@v3
    - run: uv sync

    - run: uv run ruff format --diff .
    - run: uv run ruff check .
    - run: uv run mypy .


  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: astral-sh/setup-uv@v3
    - run: uv sync

    - run: uv run pytest
