name: Continuous Integration

on: push

jobs:
  lint-and-tests:
    name: Linting & Testing
    runs-on: ubuntu-latest
    steps:
    # Setup
    - uses: actions/checkout@v3
    - uses: astral-sh/setup-uv@v3

    # Lint
    - run: uv run ruff format --diff .
    - run: uv run ruff check .
    - run: uv run mypy .

    # Test
    - run: uv run pytest
